export const EVENTS = {
  BOARD_IO: {
    ADD: 'BOARD_IO_ADD',
    REMOVE: 'BOARD_IO_REMOVE',
    CHANGED: 'BOARD_IO_CHANGED',
    CONNECTED: 'BOARD_IO_CONNECTED',
  },
  BOARD: {
    ADD: 'BOARD_ADD',
    REMOVE: 'BOARD_REMOVE',
    CHANGED: 'BOARD_CHANGED',
    CONNECTED: 'BOARD_CONNECTED',
    INIT: 'BOARD_INIT',
  }
};
