version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 3000:3000
      - 9017:9017
      - 9117:9117
    depends_on:
      - client
      - remote-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  remote-server: 
    container_name: remote-server
    build:
      context: ./remote-server
      target: remote-server-prod
    ports:
      - 4000:4000
    env_file:
      - ./remote-server/.env
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      - mongo
  client:
    container_name: client
    build:
      context: ./client
      target: client-prod
    ports:
      - 5050:5050
    links:
      - remote-server # name we use for nodeJS server
    env_file:
      - ./client/.env
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      - remote-server

  mongo:
    image: mongo:6-jammy
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: MongoDB!
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
